# Future use of this:
# Choose to build web app, native app or a mobile app.
# In case of web app, temporarily copy over package.json, index.html and such into ./src and afterwards build & clean up.
# Also possibly later make it do all the neat extra stuff?
# Maybe even integrate it with "the other" makefile in outside dir? idk!