services:
  db:
    image: postgres:16.6-alpine
    restart: always
    # Set shared memory limit when using docker-compose
    shm_size: 128mb
    ports: 
      - "5432" # This exposes it to host. Assuming it won't break anything, maybe we should remove this?
    environment:
      POSTGRES_DB: tpc_testing
      POSTGRES_USER: starr4ever
      POSTGRES_PASSWORD: hahahano
    hostname: postgres
    volumes:
      - ./toys/testing_role.sql:/docker-entrypoint-initdb.d/init.sql
    
  apisrv:
    build: .
    restart: always
    ports:
      - "58057:8057"
