[Step 1]
getResquestMethod()
where = HANDLER

[Step 2]
getRequestHeaders()
where = APIRoute (& HANDLER?)

[Step 3]
getRequestBody()
where = APIRoute
where = "in non-safe methods only (RFC 9110): so NONE of {GET,HEAD,OPTIONS,TRACE}"

[Step 4]
getResponseHeaders()
where = APIRoute & HANDLER

[Step 5]
sendResponseHeaders()
where = APIRoute & HANDLER

[Step 6]
getResponseBody()
where = APIRoute & HANDLER
