/*
 * This source file was generated by the Gradle 'init' task
 */
package lvsa.tpcalendar;

import org.junit.jupiter.api.Test;

import lvsa.tpcalendar.routes.ImATeapotDoubleColon3Router;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        ImATeapotDoubleColon3Router classUnderTest = new ImATeapotDoubleColon3Router();
        assertNotNull(classUnderTest.getResponse(), "app has a default response for /teapot endpoint.");
    }
}
